name: Publish release version

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github
          cache: 'gradle'
          settings-path: ${{ github.workspace }}
      - name: Version
        run: gradlew -v
      - name: Build
        run: gradlew build
      - name: Test
        run: gradlew test
      - name: Publish
        run: gradlew publish
